root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'ava'
extends:
  - 'eslint:recommended'
  - 'preact'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
ignorePatterns:
  - '**/*.d.ts'
rules:
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - arrowFunctions
        - methods
        - private-constructors
        - protected-constructors
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-namespace':
    - error
    - allowDeclarations: true
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-unused-vars': 'off'
  'prefer-arrow-callback':
    - error
    - allowNamedFunctions: true
  'prefer-const':
    - error
    - destructuring: 'all'
  'no-else-return': 'off'
overrides:
  - files: ['packages/*/test/**/*.{ts,tsx}']
    rules:
      'jest/expect-expect': 'off'
      'jest/no-test-callback': 'off'
