name: hawaii-bus-plus
private: true
version: 5.0.0
scripts:
  api: pnpm run api:client --filter api-gen
  build: "pnpm run build --filter client && \
    pnpm run build:ssr --filter client &&
    pnpm run api:dist --filter api-gen && \
    pnpm run build --filter prerender && \
    pnpm run workbox --filter client && \
    pnpm run build --filter functions"
  clean: >-
    del-cli "dist/**/*" "packages/**/*.js" "packages/**/*.d.ts"
    "packages/**/*.map" "packages/**/*.tsbuildinfo"
  dev: pnpm run dev --filter client
  format: prettier *.yaml *.cjs *.json .github/**/*.yml --write
  tsc: tsc --build .
dependencies:
  tslib: ^2.3.1
devDependencies:
  '@typescript-eslint/eslint-plugin': ^5.9.1
  '@typescript-eslint/parser': ^5.9.1
  del-cli: ^4.0.1
  dotenv: ^11.0.0
  eslint: ^8.6.0
  eslint-config-preact: ^1.3.0
  eslint-config-prettier: ^8.3.0
  eslint-plugin-ava: ^13.2.0
  eslint-plugin-react: ^7.28.0
  pnpm: ^6.25.1
  prettier: ~2.5.1
  typescript: ^4.8.2
