name: hawaii-bus-plus
private: true
version: 5.0.0
scripts:
  api: 'pnpm run api:client --filter @hawaii-bus-plus/api-gen'
  build: >-
    pnpm run build --filter @hawaii-bus-plus/client && pnpm run build --filter
    @hawaii-bus-plus/prerender && pnpm run build --filter
    @hawaii-bus-plus/functions && pnpm run api:dist --filter
    @hawaii-bus-plus/api-gen
  clean: >-
    del-cli packages/**/*.js packages/**/*.d.ts packages/**/*.map
    packages/**/*.tsbuildinfo
  dev: pnpm run dev --filter @hawaii-bus-plus/client
  format: prettier *.yaml *.cjs *.json .github/**/*.yaml --write
  tsc: tsc --build .
dependencies:
  tslib: ^2.1.0
devDependencies:
  '@typescript-eslint/eslint-plugin': ^4.16.1
  '@typescript-eslint/parser': ^4.16.1
  del-cli: ^3.0.1
  dotenv: ^8.2.0
  eslint: ^7.21.0
  eslint-config-preact: ^1.1.3
  eslint-config-prettier: ^7.2.0
  eslint-plugin-ava: ^11.0.0
  eslint-plugin-react: ^7.22.0
  pnpm: ^5.18.1
  prettier: ^2.2.1
  type-fest: ^0.20.2
  typescript: ^4.2.2
