name: 'hawaii-bus-plus'
private: true
version: '5.0.0'

scripts:
  api: 'pnpm run api:client --filter @hawaii-bus-plus/api-gen'
  build: 'pnpm run build --filter @hawaii-bus-plus/client && pnpm run build --filter @hawaii-bus-plus/functions && pnpm run api:dist --filter @hawaii-bus-plus/api-gen'
  clean: 'del-cli packages/**/*.js packages/**/*.d.ts packages/**/*.map packages/**/*.tsbuildinfo packages/client/public/api/**/*.json'
  dev: 'pnpm run dev --filter @hawaii-bus-plus/client'
  tsc: 'tsc --build .'

dependencies:
  'tslib': '^2.1.0'
devDependencies:
  'del-cli': '^3.0.1'
  'pnpm': '^5.16.0'
  'prettier': '^2.2.1'
  'type-fest': '^0.20.2'
  'typescript': '^4.1.3'
