name: hawaii-bus-plus
private: true
version: 5.0.0
scripts:
  api: pnpm run api:client --filter api-gen
  build: >-
    pnpm --filter client run build &&
    pnpm --filter client run build:ssr &&
    pnpm --filter api-gen run api:client &&
    pnpm --filter prerender run build &&
    pnpm --filter client run workbox &&
    pnpm --filter functions run build
  clean: >-
    del-cli "dist/**/*" "packages/**/*.js" "packages/**/*.d.ts"
    "packages/**/*.map" "packages/**/*.tsbuildinfo"
  dev: pnpm run dev --filter client
  format: prettier *.yaml *.cjs *.json .github/**/*.yml --write
  tsc: tsc --build .
dependencies:
  tslib: ^2.5.0
devDependencies:
  '@typescript-eslint/eslint-plugin': ^5.36.2
  '@typescript-eslint/parser': ^5.36.2
  del-cli: ^4.0.1
  dotenv: ^11.0.0
  eslint: ^8.35.0
  eslint-config-prettier: ^8.5.0
  eslint-plugin-ava: ^14.0.0
  eslint-plugin-react: ^7.31.7
  eslint-plugin-react-hooks: ^4.6.0
  eslint-plugin-vitest: ^0.0.54
  pnpm: ^7.9.5
  prettier: ~2.8.4
  typescript: ^4.9.5
