name: hawaii-bus-plus
private: true
version: 5.0.0
scripts:
  api: pnpm run api:client --filter @hawaii-bus-plus/api-gen
  build: >-
    pnpm run build --filter @hawaii-bus-plus/client && pnpm run api:dist
    --filter @hawaii-bus-plus/api-gen && pnpm run build --filter
    @hawaii-bus-plus/prerender && pnpm run workbox --filter
    @hawaii-bus-plus/client && pnpm run build --filter
    @hawaii-bus-plus/functions
  clean: >-
    del-cli "dist/**/*" "packages/**/*.js" "packages/**/*.d.ts"
    "packages/**/*.map" "packages/**/*.tsbuildinfo"
  dev: pnpm run dev --filter @hawaii-bus-plus/client
  format: prettier *.yaml *.cjs *.json .github/**/*.yaml --write
  tsc: tsc --build .
dependencies:
  tslib: ^2.3.1
devDependencies:
  '@typescript-eslint/eslint-plugin': ^4.33.0
  '@typescript-eslint/parser': ^4.33.0
  del-cli: ^3.0.1
  dotenv: ^10.0.0
  eslint: ^7.32.0
  eslint-config-preact: ^1.1.4
  eslint-config-prettier: ^8.3.0
  eslint-plugin-ava: ^12.0.0
  eslint-plugin-react: ^7.26.1
  pnpm: ^6.18.0
  prettier: ~2.4.1
  typescript: ^4.4.4
